version: '2.1'

networks:
  basic:

services:
  # 全局-nosql数据库mongodb
  myflag-mongo:
    image: ${IMAGE_MONGO}
    container_name: ${IMAGE_CONTAINER_MONGO}
    volumes:
      - $RUN_PATH/data-server/${IMAGE_CONTAINER_MONGO}/db:/data/db
      - $RUN_PATH/data-server/${IMAGE_CONTAINER_MONGO}/conf:/data/configdb
    command: --wiredTigerCacheSizeGB 3
    ports:
      - 9091:27017
    #mem_limit: 1500M
    networks:
      - basic

#  全局-关系型数据库mysql
  myflag-mysql:
    image: ${IMAGE_MYSQL}
    container_name: ${IMAGE_CONTAINER_MYSQL}
    volumes:
      - $RUN_PATH/data-server/${IMAGE_CONTAINER_MYSQL}/data:/var/lib/mysql
      - $RUN_PATH/data-server/${IMAGE_CONTAINER_MYSQL}/conf:/etc/mysql/conf.d
      - $RUN_PATH/data-server/${IMAGE_CONTAINER_MYSQL}/init:/docker-entrypoint-initdb.d/
    command:
      --lower_case_table_names=1
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - TZ=Asia/Shanghai
    ports:
      - 9906:3306
    networks:
      - basic

  #  全局-缓存 redis
  myflag-redis:
    image: ${IMAGE_REDIS}
    container_name: ${IMAGE_CONTAINER_REDIS}
    volumes:
      - $RUN_PATH/data-server/${IMAGE_CONTAINER_REDIS}/conf/redis.conf:/etc/redis/redis.conf:rw
      - $RUN_PATH/data-server/${IMAGE_CONTAINER_REDIS}/data:/data:rw
    ports:
      - 6379:6379
    networks:
      - basic
    command:
      redis-server /etc/redis/redis.conf --appendonly yes  --requirepass 123456

  #  jeefree
  myflag-jeefree:
    image: ${IMAGE_JEEFREE}
    container_name: ${IMAGE_CONTAINER_JEEFREE}
    volumes:
      - $RUN_PATH/data-server/${IMAGE_CONTAINER_JEEFREE}/app:/app:rw
    ports:
      - 8081:8080
    working_dir: /app
    command:
#      java -jar app.jar --jeefree.profile=/app/userfile/ --spring.redis.host=host.docker.internal --spring.datasource.druid.master.url=jdbc:mysql://host.docker.internal:3306/jeefree?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8 --spring.datasource.druid.master.username=jeefree --spring.datasource.druid.master.password=JXaWJ865HFL3B3hZ
      java -jar app.jar --jeefree.profile=/app/userfile/ --spring.redis.host=myflag-redis --spring.datasource.druid.master.url=jdbc:mysql://host.docker.internal:9906/jeefree?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8 --spring.datasource.druid.master.username=root --spring.datasource.druid.master.password=root
    networks:
      - basic

  #  ipfs单节点
  myflag-ipfs:
    image: ${IMAGE_IPFS}
    container_name: ${IMAGE_CONTAINER_IPFS}
    volumes:
      - $RUN_PATH/data-server/${IMAGE_CONTAINER_IPFS}/export:/export:rw
      - $RUN_PATH/data-server/${IMAGE_CONTAINER_IPFS}/data:/data/ipfs:rw
    ports:
      - 4001:4001
      - 5001:5001
      - 8081:8080
    networks:
      - basic

    #  消息队列
    # 4369 -- erlang发现口
    # 5672 -- client端通信口
    # 15672 -- 管理界面ui端口
    # 25672 -- server间内部通信口，集群之间
  myflag-mq:
    hostname: localhost
    container_name: ${IMAGE_CONTAINER_MQ}
    environment:
      RABBITMQ_DEFAULT_VHOST: "/test"
      RABBITMQ_DEFAULT_USER: "root"
      RABBITMQ_DEFAULT_PASS: "root"
    image: ${IMAGE_MQ}
    volumes:
#      windows下需要映射到当前windows用户的文件目录下，比如：C:\Users\${username}，未避免影响到开发，这里将该映射关闭，生产时，Linux下一定要开启
#      - $RUN_PATH/data-server/${IMAGE_CONTAINER_MQ}/data:/var/lib/rabbitmq
      - $RUN_PATH/data-server/${IMAGE_CONTAINER_MQ}/log:/var/log/rabbitmq/log
    ports:
      - 15672:15672
      - 4369:4369
      - 5672:5672
      - 25672:25672
#    command:
#      - /bin/bash
#      - -c
#      - |
#        rabbitmq-plugins enable rabbitmq_management
